// Copyright 2024 idank
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP24
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

// #define AZOTEQ_IQS5XX_TPS65
// #define AZOTEQ_IQS5XX_ROTATION_270
#define I2C_DRIVER I2CD0
#define I2C1_SCL_PIN GP1
#define I2C1_SDA_PIN GP0
#define POINTING_DEVICE_MOTION_PIN GP21

#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN NO_PIN

#define LCD_RST_PIN GP4
#define LCD_DC_PIN GP5
#define LCD_CS_PIN GP6
#define LCD_SPI_DIVISOR 4
#define LCD_WAIT_TIME 150
#define LCD_WIDTH 160
#define LCD_HEIGHT 80
#define LCD_ROTATION QP_ROTATION_270
#define LCD_OFFSET_X 1
#define LCD_OFFSET_Y 26
#define LCD_INVERT_COLOUR

#define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
//#define ST7735_NO_AUTOMATIC_VIEWPORT_OFFSETS

#define BACKLIGHT_PIN GP20
#define BACKLIGHT_PWM_DRIVER PWMD2
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_A

// Timeout configuration
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 30000
