# Enabled in users/holykeebs/rules.mk.
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = azoteq_iqs5xx

QUANTUM_PAINTER_DRIVERS += st7735_spi
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

SRC += lcd.c
